name: arc
description: "Arc - Habit Tracker Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  go_router: ^16.3.0
  google_sign_in: ^7.2.0
  logger: ^2.6.2
  dart_mappable: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.6.0

flutter:
  uses-material-design: true
